---
- hosts: hashi_west
  vars:
    region_letter: a
    os_interface: ens4 #enp0s2
    # See vars-instruqt.yml for common variables.
    arch: amd64 # arm64, amd64
  roles:
    - base
    - consul
    - docker
    - nomad

# - hosts: vaultservers
#   vars:
#     vault_ver: 1.5.5
#     arch: amd64 # arm64, amd64
#     unseal_keys_dir_output: "/tmp/unsealKey"
#     root_token_dir_output: "/tmp/rootKey"
#   roles:
#     - vault
#     - vault-init
#     - vault-unseal

  # Use tags to control tasks to run. ex nomad-install.

