- name: Reload systemd
  become: yes
  command: systemctl daemon-reload
  listen: systemd_reload

- name: Restart service dnsmasq, in all cases
  service: name=dnsmasq state=restarted
  listen: dnsmasq_restart

- name: Restart service systemd-resolved
  service: name=systemd-resolved state=restarted
  listen: systemd-resolved