---
consul_version: "0.11.1"
consul_checksum: "sha256:eb8d2461d0ca249c1f91005f878795998bdeafccfde0b9bae82343541ce65996"
consul_install_prerequisites: ['unzip']
boundary_user: "boundary"
boundary_group: "boundary"
waypoint_user: "waypoint"
waypoint_group: "waypoint"
consul_config_path: "/etc/consul.d/"
vault_ver: 1.5.5
consul_ver: 1.8.5
nomad_ver: 1.0.0-beta2
terraform_ver: 0.13.5
hashi_list:
  - vault
  - consul
  - nomad
hashi_dir:
  - vault/data
  - consul
  - nomad
arch: amd64 # arm64, amd64
base_apps_list:
  - curl
  - wget
  - jq
  - tree
  - unzip
  - dnsmasq-base
  - dnsmasq
  - resolvconf
  - postgresql-client
docker_user: ubuntu