# provider "vault" {
  # $VAULT_ADDR should be configured with the endpoint where to reach Vault API.
  # Or uncomment and update following line
  # address = "https://vault.prod.yet.org"
  # Set the namespace to use. Can set with VAULT_NAMESPACE env var. Enterprise.
  # namespace = var.namespace
# }

resource "vault_policy" "policy" {
  name = "${var.role_prefix}_policy"
  policy = file("${path.module}/../../policies/${var.vault_policy}.hcl")
}

resource "vault_auth_backend" "backend" {
  type = var.vault_auth_backend_type
  path = var.role_prefix
  description = "AppRole managed by Terraform" # forces replacement
  tune {
    default_lease_ttl = var.default_lease_ttl_seconds
    max_lease_ttl = var.max_lease_ttl_seconds
  }
}

resource "vault_approle_auth_backend_role" "role" {
  backend            = vault_auth_backend.backend.path
  role_name          = "${var.role_prefix}_approle"
  secret_id_num_uses = var.secret_id_num_uses # 0 means unlimited
  token_policies     = var.token_policies
  secret_id_ttl      = var.secret_id_ttl
  token_ttl          = var.token_ttl
}

#-> Secret id can't be deleted. Need to review
# resource "vault_approle_auth_backend_role_secret_id" "id" {
#   backend   = vault_auth_backend.backend.path
#   role_name = "${var.role_prefix}_approle"

#   metadata = <<EOT
# {
#   "source": "Generated by Terraform Vault Provider"
# }
# EOT
#   depends_on = [vault_approle_auth_backend_role.role]
# }

# output "secret_id" {
#   value = vault_approle_auth_backend_role_secret_id.id.secret_id
# }

variable "default_lease_ttl_seconds" {
  description = "Default duration of lease validity"
  default = "3600s" # Default is 0 for global
}

variable "max_lease_ttl_seconds" {
  description = "Maximum duration of lease validity"
  default = "10800s" # Default is 0 for global
}
variable "namespace" {
  description = "namespace where project will be onboarded"
  default = ""
}
variable "role_prefix" {
  description = ""
}
variable "secret_id_num_uses" {
  description = ""
}

variable "token_policies" {
  description = ""
}

variable "vault_auth_backend_type" {
  description = ""
}

variable "vault_policy" {
  description = ""
}

variable "secret_id_ttl" {
  default = 0
}

variable "token_ttl" {
  default = 0
}