# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "azure_client_id" {
  type    = string
  default = "${env("INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_SPN_ID")}"
}

variable "azure_client_secret" {
  type    = string
  default = "${env("INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_SPN_PASSWORD")}"
}

variable "azure_subscription_id" {
  type    = string
  default = "${env("INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_SUBSCRIPTION_ID")}"
}

# The amazon-ami data block is generated from your amazon builder source_ami_filter; a data
# from this block can be referenced in source and locals blocks.
# Read the documentation for data blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/data
# Read the documentation for the Amazon AMI Data Source here:
# https://www.packer.io/docs/datasources/amazon/ami
data "amazon-ami" "autogenerated_1" {
  filters = {
    name                = "ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  region      = "us-east-1"
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
# could not parse template for following block: "template: hcl2_upgrade:4: unexpected \"\\\\\" in operand"

source "amazon-ebs" "amazon-ebs-ubuntu-bionic" {
  ami_description             = "Hashistack - Ubuntu"
  ami_name                    = "hashistack-{{isotime \"2006-01-02\"}}"
  ami_regions                 = ["us-east-1"]
  ami_virtualization_type     = "hvm"
  associate_public_ip_address = true
  force_delete_snapshot       = true
  force_deregister            = true
  instance_type               = "m5.large"
  region                      = "us-east-1"
  source_ami                  = "{{ data `amazon-ami.autogenerated_1.id` }}"
  spot_price                  = "0"
  ssh_pty                     = true
  ssh_timeout                 = "5m"
  ssh_username                = "ubuntu"
  tags = {
    Name       = "Hashistack"
    OS         = "ubuntu"
    OS-Version = "bionic"
  }
}

# could not parse template for following block: "template: hcl2_upgrade:14: unexpected \"\\\\\" in operand"

source "azure-arm" "azure-ubuntu-bionic" {
  azure_tags = {
    name       = "Hashistack"
    os         = "ubuntu"
    os-version = "bionic"
  }
  client_id                         = "{{ user `azure_client_id` }}"
  client_secret                     = "{{ user `azure_client_secret` }}"
  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "18.04-LTS"
  location                          = "West US 2"
  managed_image_name                = "hashistack-{{isotime \"2006-01-02\"}}"
  managed_image_resource_group_name = "packer"
  os_type                           = "Linux"
  subscription_id                   = "{{ user `azure_subscription_id` }}"
  vm_size                           = "Standard_DS2_v2"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.amazon-ebs.amazon-ebs-ubuntu-bionic", "source.azure-arm.azure-ubuntu-bionic"]

  provisioner "shell" {
    script = "scripts/setup.sh"
  }

  provisioner "shell" {
    script = "scripts/cleanup.sh"
  }

}
