- name: Vault - Stop vault service
  become: yes
  service:
    name: vault
    state: stopped
    enabled: yes
  tags:
    - vault

- name: Delete Hashi directories - data
  become: yes
  file:
    path: /opt/{{ item }}/data
    state: absent
    mode: 0777
    owner: "{{ item }}"
    group: "{{ item }}"
  loop:
    - vault
  tags:
    - vault

