# - name: Creating vault user group
#   group: name="{{ vault_group }}"
#   become: true

- name: Create Hashi directories
  become: yes
  file:
    path: /opt/{{ item }}/data
    state: directory
    mode: 0777
    owner: "{{ item }}"
    group: "{{ item }}"
  loop:
    - vault
  tags:
    - vault
- name: Creating vault user
  become: yes
  user:
    name="{{ item }}" system=yes shell="/sbin/nologin"
    comment="nologin user" create_home="no" state=present
  loop:
    - "{{ vault_user }}"
  tags:
    - vault

# - name: Install prerequisites
#   package:
#     name: "{{ item }}"
#     update_cache: yes
#   with_items: "{{ vault_install_prerequisites }}"
#   become: yes

# - name: Download binary
#   get_url:
#     url: https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip
#     dest: /tmp/vault_{{vault_version}}_linux_amd64.zip
#     owner: "{{ vault_user }}"
#     group: "{{ vault_group }}"
#     mode: 0755
#     checksum: "{{vault_checksum}}"
#   register: vault_download

# - name: "Unzip vault archive"
#   unarchive:
#     src: "{{ vault_download.dest }}"
#     dest: /usr/local/bin
#     copy: no
#     owner: "{{ vault_user }}"
#     group: "{{ vault_group }}"
#     mode: 0755

- name: Unzip and install hashi vault
  become: yes
  unarchive:
    remote_src: yes
    src: https://releases.hashicorp.com/vault/{{vault_ver}}+ent/vault_{{vault_ver}}+ent_linux_{{arch}}.zip
    dest: /usr/bin/
  tags:
    - vault

# - name: "Set vault binary capabilities"
#   capabilities:
#     path: /usr/local/bin/vault
#     capability: cap_ipc_lock+ep
#     state: present

- name: Create service file
  become: yes
    # Ubuntu: service files are placesd here /lib/systemd/system/
    # Ubuntu: symlinked to here when enabled /etc/systemd/system/multi-user.target.wants/
  template:
    src: init.service.j2
    dest: /lib/systemd/system/
    # dest: /etc/systemd/system/vault.service
    # owner: root
    # group: root
  notify: systemd_reload
  tags:
    - vault

- name: config file
  template:
    src: vault.hcl.j2
    dest: "{{ vault_config_path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: vault service
  become: yes
  service:
    name: vault
    state: started
    enabled: yes
  tags:
    - vault