- name: Install pre-requisite apps
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ base_apps_list }}"
  tags:
    - base

- name: Add mappings to /etc/hosts
  become: yes
  blockinfile:
    backup: yes
    path: /etc/hosts
    state: present
    block: |
      {{ item.value.ip }} {{ item.key }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.key }}"
  loop: "{{ lookup('dict', host_file) }}"
  tags:
    - home

# - name: Base - Update /etc/resolv.conf via resolvconf
#   become: yes
#   # replace:
#   #   path: /etc/resolv.conf
#   #   regexp: "nameserver 127.0.0.*"
#   #   replace: "nameserver 127.0.0.1"
#   lineinfile:
#     path: /etc/resolvconf/resolv.conf.d/head
#     line: nameserver 127.0.0.1
#   tags:
#     - base

- name: Forward DNS to Consul for .consul. Update /etc/systemd/resolved.conf
  become: yes
  blockinfile:
    path: /etc/systemd/resolved.conf
    block: |
      DNS=127.0.0.1
      Domains=~consul
  notify: systemd-resolved_restart

- name: use iptables to map port 53 to 8600
  become: yes
  iptables:
    table: nat
    chain: OUTPUT
    destination: localhost
    protocol: "{{item}}"
    match: "{{item}}"
    destination_port: "53"
    jump: REDIRECT
    to_ports: "8600"
  loop:
    - tcp
    - udp
  tags:
    - base

- name: Base - Enable and start service
  become: yes
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - resolvconf
  tags:
    - base

# - name: Configure dnsmasq to forward .consul requests to consul port 8600
#   become: yes
#   copy:
#     dest: "/etc/dnsmasq.d/10-consul"
#     content: |
#       server=/consul/127.0.0.1#8600
#       # Forward everything else to Google DNS
#       server=127.0.0.53
#       cache-size=0
#   notify: dnsmasq_restart
#   tags:
#     - base

# - name: Restart service dnsmasq, in all cases
#   become: yes
#   service: name=dnsmasq state=restarted
#   ignore_errors: yes
#   tags:
#     - base
#     - dns

- name: Create HashiCups directories for Demo
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
    # owner: "{{ item }}"
    # group: "{{ item }}"
  loop:
    - /var/lib/postgresql/data
    - /opt/nomad-volumes/grafana
  tags:
    - base